version: "3.8"

services:
  # Service A - Input Handler
  service-a:
    build:
      context: .
      dockerfile: ./service-a/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_A_PORT=8080
      - SERVICE_B_URL=http://service-b:8081
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_NAME=service-a
    depends_on:
      - service-b
      - zipkin
    restart: unless-stopped
    networks:
      - app-network

  # Service B - Orchestrator
  service-b:
    build:
      context: .
      dockerfile: ./service-b/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVICE_B_PORT=8081
      - VIA_CEP_URL=https://viacep.com.br/ws
      - WEATHER_API_URL=https://api.weatherapi.com/v1/current.json
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_NAME=service-b
    depends_on:
      - zipkin
    restart: unless-stopped
    networks:
      - app-network

  # Zipkin for distributed tracing
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
